#!/bin/bash

CNTRY=`echo $2 | sed 's/ /\./g' | sed 's/\,/\./g' | sed 's/\-/\./g'`

sed  "s|METRICFILE|${1}|" R/plot.R | sed "s|COUNTRY|${CNTRY}|" | 
    sed "s|METRIC|${3}|" | R --no-save
mv rplot.jpg static/images/

